release notes for Regolith 3.1
regolith-linux/regolith-desktop-website pull request #38
Opened 2023-10-18 03:29 UTC by kgilmer

More (minor) changes expected before release.

* Fix regolith-control-center builds on manic
* Finish integrated `childe` for sway

2023-10-18 10:52 UTC, SoumyaRanjanPatnaik requested changes

2023-10-18 10:52 UTC, SoumyaRanjanPatnaik commented on content/docs/reference/Releases/regolith-3.1-release-notes.md
> +* Ubuntu 23.10 (manic) support
*mantic

2023-10-18 10:58 UTC, SoumyaRanjanPatnaik requested changes

2023-10-18 10:58 UTC, SoumyaRanjanPatnaik commented on content/docs/reference/Releases/regolith-3.1-release-notes.md
> +# Regolith 3.0 Release Notes
3.1

2023-10-18 10:58 UTC, SoumyaRanjanPatnaik commented on content/docs/reference/Releases/regolith-3.1-release-notes.md
> +[Regolith 3.0](https://github.com/orgs/regolith-linux/projects/26) is a minor release focusing on Ubuntu 23.10 support.
3.1

2023-10-18 10:58 UTC, SoumyaRanjanPatnaik commented on content/docs/reference/Releases/regolith-3.1-release-notes.md
> +## Changelog Delta from Regolith 3.0
3.1

2023-11-05 04:21 UTC, kgilmer commented on content/docs/reference/Releases/regolith-3.1-release-notes.md
> +## Changelog Delta from Regolith 3.0
this one actually should be `3.0`

2024-01-13 17:52 UTC, kgilmer commented
Ready for another pass.  @SoumyaRanjanPatnaik

2024-01-13 21:26 UTC, SoumyaRanjanPatnaik commented
Is this for the beta or the final release?

2024-01-13 21:29 UTC, SoumyaRanjanPatnaik commented
I also wonder what the status of the sway session is going to be in this release. It might be a good idea to extensively document the sway session before we release sway as stable.

2024-01-14 04:10 UTC, kgilmer commented
> Is this for the beta or the final release?

This is for beta 1.  I had hoped to get this out back in October but the portals thing happened.

> I also wonder what the status of the sway session is going to be in this release. It might be a good idea to extensively document the sway session before we release sway as stable.

What's in this release from 3.0 is in the release notes.  Regarding docs, I'd be happy to help out.  LMK if you have specifics..

2024-01-16 10:08 UTC, SoumyaRanjanPatnaik commented
Looks good. I suppose we can proceed with the release :)

2024-01-17 22:15 UTC, SoumyaRanjanPatnaik reviewed
I just noticed that `sway-regolith` is missing in this changelog. Also it seems like  `r3_1-beta1` tag (which is built by voulage [here](https://github.com/regolith-linux/voulage/blob/746bc0ef40cb87012a303dda7c9546e6370a021a/stage/testing/package-model.json#L191C1-L194C7) ) points to an older version of `sway-regolith`. However the `r3_1-beta1-ubuntu-mantic` tag does seem to package the correct version [here](https://github.com/regolith-linux/voulage/blob/746bc0ef40cb87012a303dda7c9546e6370a021a/stage/testing/ubuntu/mantic/package-model.json#L27C1-L30C7)

2024-01-18 03:21 UTC, kgilmer commented
Updated tags on `sway-regolith` and added changelog

2024-01-25 01:15 UTC, merged